import { Img } from "./Img";
import { Text } from "./Text";
import { Heading } from "./Heading";
import { Slider } from "./Slider";
import { Button } from "./Button";
import { SelectBox } from "./SelectBox";
import { Input } from "./Input";
import { RadioGroup } from "./RadioGroup";
import { GoogleMap } from "./GoogleMap";
import { Radio } from "./Radio";
export { Img, Text, Heading, Slider, Button, SelectBox, Input, RadioGroup, GoogleMap, Radio };
